SeleniumHQ/seleniumhq.github.io

.travis.yml
deploy.sh

Before merging any contributions, it is a good idea to enable a CI to check that the site builds properly.

Adding Travis CI to build site

---

site_source_files/themes/selenium/layouts/ecosystem/section.html

**This pull request is about adding lambdaTest in Functional Test Services section of ecosystem page . 🚀**
LambdaTest is a selenium-as-a-service provider that allows users to run tests on 2000+ different desktop and mobile browser environments. LambdaTest provides an online selenium gird that can be used for this.
LambdaTest is part of the Selenium ecosystem aiming to bring all testing aspects to the cloud. Hope our contribution to this field can make the life of the tester easier :slightly_smiling_face:

added lambdatest in function test services of ecosystem page.

---

docs_source_files/content/webdriver/keyboard.en.md
docs_source_files/content/webdriver/keyboard.es.md
docs_source_files/content/webdriver/keyboard.fr.md
docs_source_files/content/webdriver/keyboard.ja.md
docs_source_files/content/webdriver/keyboard.ko.md
docs_source_files/content/webdriver/keyboard.nl.md
docs_source_files/content/webdriver/keyboard.zh-cn.md

Add: Added python sample code for keyup action

---

docs_source_files/content/remote_webdriver/remote_webdriver_client.de.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.en.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.es.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.fr.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ja.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ko.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.nl.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.zh-cn.md

Without .usingServer() the local browser is started, but it's a remote WebDriver example.

Added .usingServer() to JavaScript Examples

---

docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.de.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.en.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.es.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.fr.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.ja.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.ko.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.nl.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.zh-cn.md

Added JavaScript code example for using FirefoxOptions
Making Selenium Friendlier for JS developers.

Add: Added JavaScript example for using FirefoxOptions

---

docs_source_files/content/webdriver/waits.de.md
docs_source_files/content/webdriver/waits.en.md
docs_source_files/content/webdriver/waits.es.md
docs_source_files/content/webdriver/waits.fr.md
docs_source_files/content/webdriver/waits.ja.md
docs_source_files/content/webdriver/waits.ko.md
docs_source_files/content/webdriver/waits.nl.md
docs_source_files/content/webdriver/waits.zh-cn.md

Fixing a link (incorrect URL) that is supposed to lead to the API documentation for the .NET implementation of the `ExpectedConditions` type.
The link was broken, making it hard for readers to learn about .NET's implementation of `ExpectedConditions`.
Not attaching a screenshot as the change effects behavior, not visuals.

WebDriver Waits page - Fixed broken link to .NET's ExpectedConditions type

---

docs_source_files/content/webdriver/_index.fr.md
docs_source_files/content/webdriver/keyboard.fr.md
docs_source_files/content/webdriver/web_element.fr.md

Translating document webelement and keyboard to french

Modify: Translated [EN] -> FR: Webdriver-> Keybaord and webelement doc

---

docs_source_files/content/driver_idiosyncrasies/_index.ja.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.ja.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.ja.md

This PR contains new Japanese translation of Driver Idiosyncrasies:
- driver_idiosyncrasies/_index.ja.md
- driver_idiosyncrasies/driver_specific_capabilities.ja.md
- driver_idiosyncrasies/shared_capabilities.ja.md

Add Japanese translation of "Driver Idiosyncrasies"

---

docs_source_files/content/getting_started_with_webdriver/locating_elements.fr.md
docs_source_files/content/getting_started_with_webdriver/third_party_drivers_and_plugins.fr.md

Documents are translated to french already, info bar can be removed.

Modify: Removing info section for translated pages

---

docs_source_files/content/worst_practices/captchas.zh-cn.md

Add Chinese translation of "captchas" 
- worst_practices/captchas.zh-cn.md

Add Chinese translation of "captchas"

---

docs_source_files/content/guidelines_and_recommendations/fresh_browser_per_test.fr.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.fr.md
docs_source_files/content/guidelines_and_recommendations/test_independency.fr.md

Translating below docs to french
1. fresh_browser_per_test.fr.md
2. improved_reporting.fr.md
3. test_dependency.fr.md

Modify:[EN]->[FR] Translating guidelines and recommendations

---

docs_source_files/content/support_packages/working_with_cookies.de.md
docs_source_files/content/support_packages/working_with_cookies.en.md
docs_source_files/content/support_packages/working_with_cookies.es.md
docs_source_files/content/support_packages/working_with_cookies.fr.md
docs_source_files/content/support_packages/working_with_cookies.ja.md
docs_source_files/content/support_packages/working_with_cookies.ko.md
docs_source_files/content/support_packages/working_with_cookies.nl.md
docs_source_files/content/support_packages/working_with_cookies.zh-cn.md

Adding sameSite cookie  attribute to cookie document.
Currently feature is available for webdriverJS bindings with commit https://github.com/SeleniumHQ/selenium/pull/7901.
Feature is described in [webdriver](https://w3c.github.io/webdriver/#cookies) living document

Add: Adding sameSite cookie attribute to cookie document

---

docs_source_files/content/webdriver/http_proxies.ja.md

Japanese translation of https://github.com/SeleniumHQ/seleniumhq.github.io/pull/281

Add Japanese translation of "Http Proxies"

---

docs_source_files/content/support_packages/working_with_cookies.de.md
docs_source_files/content/support_packages/working_with_cookies.en.md
docs_source_files/content/support_packages/working_with_cookies.es.md
docs_source_files/content/support_packages/working_with_cookies.fr.md
docs_source_files/content/support_packages/working_with_cookies.ja.md
docs_source_files/content/support_packages/working_with_cookies.ko.md
docs_source_files/content/support_packages/working_with_cookies.nl.md
docs_source_files/content/support_packages/working_with_cookies.zh-cn.md

sameSite cookie attribute is implemented in chrome80 + versions. FF and safari browsers still need to implement. 
So adding a note section for sameSite for now. Once feature lands on every browser we can eventually remote/modify the note section accordingly

Add: Adding note section for sameSite cookie as the feature is only landed in chrome 

---

docs_source_files/content/driver_idiosyncrasies/shared_capabilities.de.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.en.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.es.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.fr.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.ja.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.ko.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.nl.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.zh-cn.md

Adding shared capabilities `platformName` and 'acceptInsecureCerts' into sharedCapabilities.md

Add: Adding shared capabilities platformName and acceptInsecureCerts

---

docs_source_files/content/getting_started_with_webdriver/locating_elements.es.md
docs_source_files/content/webdriver/_index.es.md
docs_source_files/content/webdriver/driver_requirements.es.md
docs_source_files/content/webdriver/http_proxies.es.md
docs_source_files/content/webdriver/page_loading_strategy.es.md
docs_source_files/content/webdriver/support_classes.es.md
docs_source_files/content/webdriver/web_element.es.md

- Add spanish translation to websites
- Improve term translation

Add spanish translation to sites

---

docs_source_files/content/driver_idiosyncrasies/shared_capabilities.ja.md

Add Japanese translation of 
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/345

Add Japanese translation of #345

---

docs_source_files/content/worst_practices/captchas.es.md
docs_source_files/content/worst_practices/file_downloads.es.md

- Improve the translation from catchas pages and delete notice info box
- Add a new translation for file downloads page

Worst practices translations spanish

---

docs_source_files/content/worst_practices/gmail_email_and_facebook_logins.es.md

Add translation to spanish for gmail email and facebook page

Translate gmail and facebook page to spanish

---

docs_source_files/content/guidelines_and_recommendations/_index.en.md
docs_source_files/content/guidelines_and_recommendations/_index.es.md
docs_source_files/content/guidelines_and_recommendations/_index.fr.md
docs_source_files/content/guidelines_and_recommendations/_index.ko.md
docs_source_files/content/guidelines_and_recommendations/_index.nl.md
docs_source_files/content/guidelines_and_recommendations/avoid_sharing_state.es.md
docs_source_files/content/guidelines_and_recommendations/consider_using_a_fluent_api.es.md
docs_source_files/content/guidelines_and_recommendations/fresh_browser_per_test.es.md
docs_source_files/content/guidelines_and_recommendations/generating_application_state.es.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.de.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.en.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.es.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.fr.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.ja.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.ko.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.nl.md
docs_source_files/content/guidelines_and_recommendations/improved_reporting.zh-cn.md
docs_source_files/content/guidelines_and_recommendations/mock_external_services.es.md
docs_source_files/content/guidelines_and_recommendations/page_object_models.es.md
docs_source_files/content/guidelines_and_recommendations/test_independency.es.md
docs_source_files/content/remote_webdriver/_index.es.md
docs_source_files/content/webdriver/js_alerts_prompts_and_confirmations.es.md

- Add spanish translation to most of the guides topic
- Fix some readability issues in reports sites in all languages
- Update some terms

Add spanish translation and update some terms

---

docs_source_files/content/remote_webdriver/remote_webdriver_client.de.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.en.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.es.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.fr.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ja.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ko.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.nl.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.zh-cn.md

for remote client, we should use LocalFileDetector instead of UselessFileDetector, the latter do nothing

Modify: Use LocalFileDetector in Python

---

build-site.sh
site_source_files/themes/selenium/layouts/partials/banner-notification.html
site_source_files/themes/selenium/static/css/index.css

Home page will look like this:

Black Lives Matter

---

docs_source_files/content/getting_started_with_webdriver/_index.ko.md
docs_source_files/content/getting_started_with_webdriver/browsers.ko.md
docs_source_files/content/getting_started_with_webdriver/third_party_drivers_and_plugins.ko.md
docs_source_files/content/selenium_installation/_index.ko.md

- Translate _selenium_installation\_index.ko.md_ to Korean
- Translate _getting_started_with_webdriver\_index.ko.md_ to Korean
- Translate _getting_started_with_webdriver\browsers.md_ to Korean
- Translate _getting_started_with_webdriver\third_party_drivers_and_plugins.ko.md_ to Korean

Add Korean Translation of "getting started with webdriver"

---

docs_source_files/content/support_packages/chrome_devtools.ja.md

Translating document "Chrome Devtools"
- content/support_packages/chrome_devtools.ja.md

Add Japanese transration of Chrome Devtools

---

docs_source_files/content/driver_idiosyncrasies/shared_capabilities.zh-cn.md

- driver_idiosyncrasies/shared_capabilities.zh-cn.md
Update Chinese translation of "shared_capabilities"
- Update Chinese translation
- Remove duplicate part

Update Chinese translation of "shared_capabilities"
