SeleniumHQ/seleniumhq.github.io

docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.es.md

Completing the translation of #17

Mouse and keyboard actions in detail using c#

---

docs_source_files/content/remote_webdriver/remote_webdriver_client.es.md

Completing the translation of #15

C# Remote WebDriver Client Example

---

docs_source_files/content/support_packages/browser_navigation.es.md

Completing the translation for #16

Browser navigation c# example

---

docs_source_files/content/webdriver/support_classes.en.md
docs_source_files/content/webdriver/support_classes.es.md
docs_source_files/content/webdriver/support_classes.fr.md
docs_source_files/content/webdriver/support_classes.ja.md
docs_source_files/content/webdriver/support_classes.nl.md
docs_source_files/content/webdriver/support_classes.zh-cn.md
docs_source_files/content/webdriver/waits.en.md

To help highlight the correct use of the class to aid test design and architecture

Add information on the use of ThreadGuard Support class

---

docs_source_files/content/getting_started/_index.ja.md
docs_source_files/content/getting_started/quick.ja.md

This PR contains new Japanese translation of:
* Getting started
* Quick tour

Add Japanese translation of "Getting Started"

---

docs_source_files/content/selenium_installation/_index.ja.md
docs_source_files/content/selenium_installation/installing_selenium_libraries.ja.md
docs_source_files/content/selenium_installation/installing_standalone_server.ja.md
docs_source_files/content/selenium_installation/installing_webdriver_binaries.ja.md

This PR contains new Japanese translation of:
* Selenium Installation
* Installing Selenium libraries
* Installing WebDriver binaries
* Installing Standalone server

Add Japanese translation of "Selenium Installation"

---

ecosystem/index.html

added Selenium Box to the ecosystem page

added Selenium Box to ecosystem page

---

ecosystem/index.html

Added Selenide (Open Source Selenium Java Library) with description to Ecosystem

---

docs_source_files/content/worst_practices/_index.es.md

Update of page.
**Note.-**
I noticed that some pages of the documentation in Spanish were badly translated. I don't know if a service translator, like Google, was used but if you read the text and titles of the translated pages you will notice the literal translation.
I don't pretend to be a professional translator. It's just an observation.

Update of Wors Practices page (Spanish version)

---

docs_source_files/content/CONTRIBUTING.en.md
docs_source_files/content/CONTRIBUTING.es.md
docs_source_files/content/CONTRIBUTING.fr.md
docs_source_files/content/CONTRIBUTING.ja.md
docs_source_files/content/CONTRIBUTING.ko.md
docs_source_files/content/CONTRIBUTING.nl.md
docs_source_files/content/CONTRIBUTING.zh-cn.md

Updating contribution docs

---

docs_source_files/content/CONTRIBUTING.en.md
docs_source_files/content/CONTRIBUTING.es.md
docs_source_files/content/CONTRIBUTING.fr.md
docs_source_files/content/CONTRIBUTING.ja.md
docs_source_files/content/CONTRIBUTING.ko.md
docs_source_files/content/CONTRIBUTING.nl.md
docs_source_files/content/CONTRIBUTING.zh-cn.md
docs_source_files/content/webdriver/keyboard.en.md
docs_source_files/content/webdriver/keyboard.es.md
docs_source_files/content/webdriver/keyboard.fr.md
docs_source_files/content/webdriver/keyboard.ja.md
docs_source_files/content/webdriver/keyboard.ko.md
docs_source_files/content/webdriver/keyboard.nl.md
docs_source_files/content/webdriver/keyboard.zh-cn.md

Signed-off-by: Sri Harsha <sri_harsha509@hotmail.com>

Add: Added doc for keyDown in Keyboard actions

---

docs_source_files/content/webdriver/keyboard.en.md
docs_source_files/content/webdriver/keyboard.es.md
docs_source_files/content/webdriver/keyboard.fr.md
docs_source_files/content/webdriver/keyboard.ja.md
docs_source_files/content/webdriver/keyboard.ko.md
docs_source_files/content/webdriver/keyboard.nl.md
docs_source_files/content/webdriver/keyboard.zh-cn.md

KeyDown (Java, Python, CSharp) Translation Completed

---

site_source_files/themes/selenium/layouts/ecosystem/section.html

Add link to Agiletestware Bumblebee (https://www.agiletestware.com/bumblebee) into list of tools with Selenium support.
Add a link to Agiletestware Bumblebee tool which integrates Java-based Selenium tests with Microfocus ALM (former HP ALM)
Screenshots:
Before:
After:

Add link to Agiletestware Bumblebee into tools

---

docs_source_files/content/webdriver/keyboard.en.md
docs_source_files/content/webdriver/keyboard.es.md
docs_source_files/content/webdriver/keyboard.fr.md
docs_source_files/content/webdriver/keyboard.ja.md
docs_source_files/content/webdriver/keyboard.ko.md
docs_source_files/content/webdriver/keyboard.nl.md
docs_source_files/content/webdriver/keyboard.zh-cn.md

Added keyUp documentation and sample code in Java and JavaScript

---

docs_source_files/content/webdriver/waits.de.md
docs_source_files/content/webdriver/waits.es.md
docs_source_files/content/webdriver/waits.fr.md
docs_source_files/content/webdriver/waits.ja.md
docs_source_files/content/webdriver/waits.ko.md
docs_source_files/content/webdriver/waits.nl.md
docs_source_files/content/webdriver/waits.zh-cn.md

Modify: Updated the code change for other translated pages too

---

docs_source_files/content/webdriver/waits.de.md
docs_source_files/content/webdriver/waits.en.md
docs_source_files/content/webdriver/waits.es.md
docs_source_files/content/webdriver/waits.fr.md
docs_source_files/content/webdriver/waits.ja.md
docs_source_files/content/webdriver/waits.ko.md
docs_source_files/content/webdriver/waits.nl.md
docs_source_files/content/webdriver/waits.zh-cn.md

Signed-off-by: Sri Harsha <sri_harsha509@hotmail.com>

Modify: Updating code sample to match other examples in this section

---

docs_source_files/content/remote_webdriver/remote_webdriver_client.de.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.en.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.es.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.fr.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ja.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ko.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.nl.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.zh-cn.md

Add: Added python code sample for remote webdriver client-> local file detector

---

docs_source_files/content/support_packages/browser_navigation.de.md
docs_source_files/content/support_packages/browser_navigation.en.md
docs_source_files/content/support_packages/browser_navigation.es.md
docs_source_files/content/support_packages/browser_navigation.fr.md
docs_source_files/content/support_packages/browser_navigation.ja.md
docs_source_files/content/support_packages/browser_navigation.ko.md
docs_source_files/content/support_packages/browser_navigation.nl.md
docs_source_files/content/support_packages/browser_navigation.zh-cn.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.de.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.en.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.es.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.fr.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.ja.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.ko.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.nl.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.zh-cn.md

Modify: Updated sample code in mouse and keyboard actions

---

docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.de.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.en.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.es.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.fr.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.ja.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.ko.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.nl.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.zh-cn.md

Signed-off-by: Sri Harsha <sri_harsha509@hotmail.com>

Add: Added JS sample code for mouse actions in support packages

---

docs_source_files/content/remote_webdriver/remote_webdriver_client.de.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.en.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.es.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.fr.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ja.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ko.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.nl.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.zh-cn.md
docs_source_files/content/support_packages/working_with_cookies.de.md
docs_source_files/content/support_packages/working_with_cookies.en.md
docs_source_files/content/support_packages/working_with_cookies.es.md
docs_source_files/content/support_packages/working_with_cookies.fr.md
docs_source_files/content/support_packages/working_with_cookies.ja.md
docs_source_files/content/support_packages/working_with_cookies.ko.md
docs_source_files/content/support_packages/working_with_cookies.nl.md
docs_source_files/content/support_packages/working_with_cookies.zh-cn.md

Modify: Updated C# and JS code samples as per the usage

---

docs_source_files/content/getting_started_with_webdriver/third_party_drivers_and_plugins.zh-cn.md

Translate third_party_drivers_and_plugins.zh-cn.md to Chinese.
I translate this file from English to Chinese.
I am a native Chinese, translate this file can make me convenient to read this again when  I need. And conveniently others people too.

Translate third_party_drivers_and_plugins.zh-cn.md to Chinese.

---

docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.zh-cn.md

Translate performing_actions_on_the_aut.zh-cn.md from English to Chinese.
Just translate performing_actions_on_the_aut.zh-cn.md from English to Chinese.
For Chinese users read conveniently.

Translate performing_actions_on_the_aut.zh-cn.md

---

docs_source_files/content/webdriver/keyboard.de.md
docs_source_files/content/webdriver/keyboard.en.md
docs_source_files/content/webdriver/keyboard.es.md
docs_source_files/content/webdriver/keyboard.fr.md
docs_source_files/content/webdriver/keyboard.ja.md
docs_source_files/content/webdriver/keyboard.ko.md
docs_source_files/content/webdriver/keyboard.nl.md
docs_source_files/content/webdriver/keyboard.zh-cn.md
docs_source_files/content/webdriver/waits.de.md
docs_source_files/content/webdriver/waits.en.md
docs_source_files/content/webdriver/waits.es.md
docs_source_files/content/webdriver/waits.fr.md
docs_source_files/content/webdriver/waits.ja.md
docs_source_files/content/webdriver/waits.ko.md
docs_source_files/content/webdriver/waits.nl.md
docs_source_files/content/webdriver/waits.zh-cn.md
docs_source_files/content/webdriver/web_element.de.md
docs_source_files/content/webdriver/web_element.en.md
docs_source_files/content/webdriver/web_element.es.md
docs_source_files/content/webdriver/web_element.fr.md
docs_source_files/content/webdriver/web_element.ja.md
docs_source_files/content/webdriver/web_element.ko.md
docs_source_files/content/webdriver/web_element.nl.md
docs_source_files/content/webdriver/web_element.zh-cn.md

Modify: Removed awaits for findElement (JavaScript)

---

docs_source_files/content/getting_started_with_webdriver/locating_elements.de.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.en.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.es.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.fr.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.ja.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.ko.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.nl.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.zh-cn.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.de.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.en.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.es.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.fr.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.ja.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.ko.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.nl.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.zh-cn.md
docs_source_files/content/webdriver/browser_manipulation.de.md
docs_source_files/content/webdriver/browser_manipulation.en.md
docs_source_files/content/webdriver/browser_manipulation.es.md
docs_source_files/content/webdriver/browser_manipulation.fr.md
docs_source_files/content/webdriver/browser_manipulation.ja.md
docs_source_files/content/webdriver/browser_manipulation.ko.md
docs_source_files/content/webdriver/browser_manipulation.nl.md
docs_source_files/content/webdriver/browser_manipulation.zh-cn.md

Signed-off-by: Sri Harsha <sri_harsha509@hotmail.com>

Modify: Removed unnecessary awaits for findElement (JavaScript)

---

docs_source_files/content/_index.de.md
docs_source_files/content/_index.en.md
docs_source_files/content/_index.es.md
docs_source_files/content/_index.fr.md
docs_source_files/content/_index.ja.md
docs_source_files/content/_index.ko.md
docs_source_files/content/_index.nl.md
docs_source_files/content/_index.zh-cn.md
docs_source_files/content/webdriver/browser_manipulation.de.md
docs_source_files/content/webdriver/browser_manipulation.en.md
docs_source_files/content/webdriver/browser_manipulation.es.md
docs_source_files/content/webdriver/browser_manipulation.fr.md
docs_source_files/content/webdriver/browser_manipulation.ja.md
docs_source_files/content/webdriver/browser_manipulation.ko.md
docs_source_files/content/webdriver/browser_manipulation.nl.md
docs_source_files/content/webdriver/browser_manipulation.zh-cn.md
docs_source_files/content/webdriver/keyboard.de.md
docs_source_files/content/webdriver/keyboard.en.md
docs_source_files/content/webdriver/keyboard.es.md
docs_source_files/content/webdriver/keyboard.fr.md
docs_source_files/content/webdriver/keyboard.ja.md
docs_source_files/content/webdriver/keyboard.ko.md
docs_source_files/content/webdriver/keyboard.nl.md
docs_source_files/content/webdriver/keyboard.zh-cn.md

Modify: Revamped kotlin code samples and document update in browser manipulation

---

docs_source_files/content/webdriver/web_element.de.md
docs_source_files/content/webdriver/web_element.en.md
docs_source_files/content/webdriver/web_element.es.md
docs_source_files/content/webdriver/web_element.fr.md
docs_source_files/content/webdriver/web_element.ja.md
docs_source_files/content/webdriver/web_element.ko.md
docs_source_files/content/webdriver/web_element.nl.md
docs_source_files/content/webdriver/web_element.zh-cn.md

Modify: Revamp web element document 

---

docs_source_files/content/introduction/types_of_testing.de.md
docs_source_files/content/introduction/types_of_testing.en.md
docs_source_files/content/introduction/types_of_testing.es.md
docs_source_files/content/introduction/types_of_testing.fr.md
docs_source_files/content/introduction/types_of_testing.ja.md
docs_source_files/content/introduction/types_of_testing.ko.md
docs_source_files/content/introduction/types_of_testing.nl.md
docs_source_files/content/introduction/types_of_testing.zh-cn.md
docs_source_files/content/webdriver/web_element.de.md
docs_source_files/content/webdriver/web_element.en.md
docs_source_files/content/webdriver/web_element.es.md
docs_source_files/content/webdriver/web_element.fr.md
docs_source_files/content/webdriver/web_element.ja.md
docs_source_files/content/webdriver/web_element.ko.md
docs_source_files/content/webdriver/web_element.nl.md
docs_source_files/content/webdriver/web_element.zh-cn.md

Added 'FindElements from element' to webelement documentation

Add: Adding findElements from element to webelement doc

---

docs_source_files/content/grid/_index.zh-cn.md
docs_source_files/content/grid/components_of_a_grid.zh-cn.md
docs_source_files/content/grid/purposes_and_main_functionalities.zh-cn.md
docs_source_files/content/grid/setting_up_your_own_grid.zh-cn.md
docs_source_files/content/grid/when_to_use_grid.zh-cn.md

Translate Chapter Grid to Chinese.
Translate below 4 files
docs_source_files/content/grid/_index.zh-cn.md
docs_source_files/content/grid/components_of_a_grid.zh-cn.md
docs_source_files/content/grid/purposes_and_main_functionalities.zh-cn.md
docs_source_files/content/grid/setting_up_your_own_grid.zh-cn.md
docs_source_files/content/grid/when_to_use_grid.zh-cn.md
These page do not have Chinese Version

translate Chapter Grid to chinese

---

docs_source_files/content/getting_started_with_webdriver/_index.ja.md
docs_source_files/content/getting_started_with_webdriver/browsers.ja.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.ja.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.ja.md
docs_source_files/content/getting_started_with_webdriver/third_party_drivers_and_plugins.ja.md

This PR contains new Japanese translation of:
* Getting started with WebDriver
* Index
* Browsers
* Third party drivers and plugins
* Locating elements
* Performing actions on the AUT

Add Japanese translation of "Getting started with WebDriver"

---

docs_source_files/content/front_matter/typographical_conventions.de.md

German translation for typhographical and conventions
Missing german translation for that page
- [] Improved translation

German Translation for typographical and conventions

---

docs_source_files/content/getting_started_with_webdriver/browsers.de.md

German translation for browsers
Missing german translation for that page
- [] Improved translation

German translation for browsers

---

docs_source_files/content/webdriver/web_element.de.md
docs_source_files/content/webdriver/web_element.en.md
docs_source_files/content/webdriver/web_element.es.md
docs_source_files/content/webdriver/web_element.fr.md
docs_source_files/content/webdriver/web_element.ja.md
docs_source_files/content/webdriver/web_element.ko.md
docs_source_files/content/webdriver/web_element.nl.md
docs_source_files/content/webdriver/web_element.zh-cn.md

Signed-off-by: sri harsha <sri_harsha509@hotmail.com>

Modify: Updated code samples to target same browser

---

docs_source_files/content/introduction/the_selenium_project_and_tools.fr.md

Translated document in section introduction -> ''Selenium_project_and_tools"  from English to French

Modify: Translated[EN-FR] Introduction -> selenium_project_and_tools page

---

docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.de.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.en.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.es.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.fr.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.ja.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.ko.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.nl.md
docs_source_files/content/support_packages/mouse_and_keyboard_actions_in_detail.zh-cn.md

Add: Added python and csharp code samples in doc Mouse action in detail 

---

docs_source_files/content/remote_webdriver/_index.ja.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.ja.md
docs_source_files/content/remote_webdriver/remote_webdriver_server.ja.md

This PR contains new Japanese translation of remote webdriver:
- remote_webdriver/_index.ja.md
- remote_webdriver/remote_webdriver_client.ja.md
- remote_webdriver/remote_webdriver_server.ja.md

Add Japanese translation of "RemoteWebDriver"

---

docs_source_files/content/introduction/on_test_automation.fr.md

Translating document "introduction-> on test automation" from english to french

Modify: [EN]->[FR]: Introduction-> translating on test automation

---

docs_source_files/content/webdriver/page_loading_strategy.de.md
docs_source_files/content/webdriver/page_loading_strategy.en.md
docs_source_files/content/webdriver/page_loading_strategy.es.md
docs_source_files/content/webdriver/page_loading_strategy.fr.md
docs_source_files/content/webdriver/page_loading_strategy.ja.md
docs_source_files/content/webdriver/page_loading_strategy.ko.md
docs_source_files/content/webdriver/page_loading_strategy.nl.md
docs_source_files/content/webdriver/page_loading_strategy.zh-cn.md

Added ruby code samples for page_load_strategy. Code samples tested with selenium-4-4.0.0alpha4 [ruby] in chrome and firefox

Add: Adding Ruby code sample for page_load_strategy

---

docs_source_files/content/webdriver/page_loading_strategy.de.md
docs_source_files/content/webdriver/page_loading_strategy.en.md
docs_source_files/content/webdriver/page_loading_strategy.es.md
docs_source_files/content/webdriver/page_loading_strategy.fr.md
docs_source_files/content/webdriver/page_loading_strategy.ja.md
docs_source_files/content/webdriver/page_loading_strategy.ko.md
docs_source_files/content/webdriver/page_loading_strategy.nl.md
docs_source_files/content/webdriver/page_loading_strategy.zh-cn.md

C-sharp code samples for pageLoadStartegy. Tested in chrome and FF with Selenium-alpha-4

Add: Adding C# code samples for page load strategy

---

docs_source_files/content/webdriver/page_loading_strategy.fr.md

Translating document page load strategy to french

Modify: [EN]->[FR] Translating document page load strategy

---

docs_source_files/content/support_packages/working_with_cookies.de.md
docs_source_files/content/support_packages/working_with_cookies.en.md
docs_source_files/content/support_packages/working_with_cookies.es.md
docs_source_files/content/support_packages/working_with_cookies.fr.md
docs_source_files/content/support_packages/working_with_cookies.ja.md
docs_source_files/content/support_packages/working_with_cookies.ko.md
docs_source_files/content/support_packages/working_with_cookies.nl.md
docs_source_files/content/support_packages/working_with_cookies.zh-cn.md

JS code sample for sameSite cookie attribute. tested With selenium-webdriver[js] alpha 7 in chrome 80

Add: Adding JS code sample for sameSite cookie attribute

---

docs_source_files/content/driver_idiosyncrasies/shared_capabilities.de.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.en.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.es.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.fr.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.ja.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.ko.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.nl.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.zh-cn.md

Thought of including `firstMatch` and `alwaysMatch` capabilities as they are common/shared capabilities to all browsers

Add: Adding shared capabilities browserName and browserVersion 

---

site_source_files/content/downloads/C#.md

Selenium4-Alpha5 released for .Net bindings. Updating the downloads section for the same.

Modify: Updating .Net alpha release version in downloads section

---

docs_source_files/content/support_packages/working_with_cookies.es.md

Translate working with cookies page to spanish

Translate working with cookies to spanish

---

docs_source_files/content/getting_started/quick.es.md

Translate getting_started/quick page to spanish

Translate getting started quick page to spanish

---

docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.es.md

Translate driver specific capabilities page to spanish

Driver specific capabilities spanish

---

docs_source_files/content/grid/components_of_a_grid.es.md

Add translation to Spanish for the components of a grid page

Translate components of a grid page to spanish

---

docs_source_files/content/remote_webdriver/_index.es.md
docs_source_files/content/remote_webdriver/remote_webdriver_client.es.md
docs_source_files/content/remote_webdriver/remote_webdriver_server.es.md
docs_source_files/content/webdriver/js_alerts_prompts_and_confirmations.es.md
docs_source_files/content/webdriver/keyboard.es.md

- Adds spanish translation to remote webdriver
- Improves translations on js alerts site

Add spanish translations

---

docs_source_files/content/guidelines_and_recommendations/domain_specific_language.es.md
docs_source_files/content/worst_practices/link_spidering.es.md

- Add spanish translation to dsl site
- Add spanish translation to link spidering

Add spanish translation to the dsl site

---

docs_source_files/content/legacy_docs/_index.es.md
docs_source_files/content/legacy_docs/html-runner.es.md
docs_source_files/content/legacy_docs/selenium_rc.es.md

- Translates index and html runner
- Translates part of RC

Add spanish translation in legacy sites

---

docs_source_files/content/legacy_docs/migrating_from_rc_to_webdriver.es.md

- Add spanish translation to the RC to Webdriver page

Add spanish translation for rc to webdriver

---

docs_source_files/content/legacy_docs/migrating_from_rc_to_webdriver.zh-cn.md

Add Chinese translation of "migrating_from_rc_to_webdriver"
- legacy_docs/migrating_from_rc_to_webdriver.zh-cn.md

Add Chinese translation of "migrating_from_rc_to_webdriver"

---

docs_source_files/content/legacy_docs/_index.es.md
docs_source_files/content/legacy_docs/selenium_rc.es.md

- Add more spanish translations to the legacy rc site
- Improve translations in the legacy index

Add more spanish translation to rc site

---

docs_source_files/content/legacy_docs/selenium_rc.en.md
docs_source_files/content/legacy_docs/selenium_rc.es.md
docs_source_files/content/legacy_docs/selenium_rc.fr.md
docs_source_files/content/legacy_docs/selenium_rc.ko.md
docs_source_files/content/legacy_docs/selenium_rc.nl.md

- Add more spanish translations to the RC site

Continue spanish translations to the RC site

---

docs_source_files/content/legacy_docs/selenium_rc.de.md
docs_source_files/content/legacy_docs/selenium_rc.en.md
docs_source_files/content/legacy_docs/selenium_rc.es.md
docs_source_files/content/legacy_docs/selenium_rc.fr.md
docs_source_files/content/legacy_docs/selenium_rc.ko.md
docs_source_files/content/legacy_docs/selenium_rc.nl.md

- Adds translation to JS section
- Adds translation to Server section
- Fix typo in other languages

Add translations to js and server in RC site

---

docs_source_files/content/webdriver/browser_manipulation.de.md
docs_source_files/content/webdriver/browser_manipulation.en.md
docs_source_files/content/webdriver/browser_manipulation.es.md
docs_source_files/content/webdriver/browser_manipulation.fr.md
docs_source_files/content/webdriver/browser_manipulation.ja.md
docs_source_files/content/webdriver/browser_manipulation.ko.md
docs_source_files/content/webdriver/browser_manipulation.nl.md
docs_source_files/content/webdriver/browser_manipulation.zh-cn.md

Kotlin sample codes in "Browser manipulation" section had some invalid codes.
- invalid or bad syntax
- remove unnecessary semicolons
- fix invalid declaration of a variable
- fix invalid calling setter
- using property syntax actively
- fix indentation misalignment
Fix examples.

Fix Kotlin sample codes in "Browser manipulation" section

---

docs_source_files/content/legacy_docs/selenium_rc.es.md

- Adds spanish translation to server logging in RC site
- Fix untranslated title header typo
- Fix untranslated paragraph typo

Add spanish translations to server logging

---

docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.de.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.en.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.es.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.fr.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.ja.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.ko.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.nl.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.zh-cn.md

Here I have added Java code snippet for `silent` an Internet Driver specific capability [link](https://www.selenium.dev/documentation/en/driver_idiosyncrasies/driver_specific_capabilities/#silent)
This change will help users with a code snippet example.

Code Snippet: Silent option for Internet driver specific capabilities 

---

docs_source_files/content/introduction/about_this_documentation.ko.md
docs_source_files/content/introduction/the_selenium_project_and_tools.ko.md

- Adds Korean translation to <about_this_documentation>
- Adds Korean translation to <the_selenium_project_and_tools>

Add Korean translation of "Introduction"

---

docs_source_files/content/legacy_docs/selenium_rc.es.md

- Add more spanish translations to RC site

Add more spanish translations to proxy injection

---

docs_source_files/content/legacy_docs/selenium_rc.es.md

- Add translation to common problems
- Add translation to using multiple browser

Add spanish translation to common issues in RC site

---

docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.de.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.en.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.es.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.fr.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.ja.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.ko.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.nl.md
docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.zh-cn.md

CodeSnippet of C# for IE forceCreateProcessApi and Command-Line Options

---

docs_source_files/content/legacy_docs/selenium_rc.es.md

- Finish spanish translation to RC site

Add spanish translation to remaining RC sections

---

docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.ja.md
docs_source_files/content/driver_idiosyncrasies/shared_capabilities.ja.md
docs_source_files/content/getting_started/quick.ja.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.ja.md
docs_source_files/content/webdriver/browser_manipulation.ja.md
docs_source_files/content/webdriver/keyboard.ja.md

Translate some pages into Japanese
translated the recently added contents below.
- content/driver_idiosyncrasies/driver_specific_capabilities.ja.md
- content/driver_idiosyncrasies/shared_capabilities.ja.md
- content/getting_started/quick.ja.md
- content/getting_started_with_webdriver/locating_elements.ja.md
- content/webdriver/browser_manipulation.ja.md
- content/webdriver/keyboard.ja.md

Translate some pages into Japanese

---

site_source_files/content/blog/2020/how-selenium-works-transport.md

Cross posting blog post with details on how Selenium works
More content for the blog
- [ x ] blog post
- [ x ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ x ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

How Selenium Works - Episode 1

---

docs_source_files/content/getting_started_with_webdriver/locating_elements.ko.md
docs_source_files/content/getting_started_with_webdriver/performing_actions_on_the_aut.ko.md

Adds Korean translation to "Locating elements" and "Performing actions on the AUT*"

Add Korean translation of "Locating elements" and "Performing actions on the AUT*"

---

docs_source_files/content/webdriver/driver_requirements.ko.md

Added Korean translation of "Driver requirements" part
Add Korean translation of "Driver requirements"

Add Korean translation of "Driver requirements"

---

docs_source_files/content/grid/_index.ko.md
docs_source_files/content/grid/purposes_and_main_functionalities.ko.md
docs_source_files/content/selenium_installation/installing_standalone_server.ko.md

Add Korean translation of "grid_index" and "grid_purposes and main functionalities" and "installing Standalone server"

Add Korean translation of "grid_index" and "grid_purposes and main functionalities" and "installing Standalone server"

---

docs_source_files/content/worst_practices/two_factor_authentication.ja.md

Add Japanese transration of two factor authentication
translated the recently added contents below.
- content/worst_practices/two_factor_authentication.ja.md

Add Japanese transration of two factor authentication

---

docs_source_files/content/support_packages/chrome_devtools.en.md
docs_source_files/content/support_packages/chrome_devtools.zh-cn.md

update Chrome DevTools Protocol in chrome_devtools.en.md
Localization zh-cn
Chrome DevTools Protocol maybe better.

Localization & terminology update

---

site_source_files/themes/selenium/layouts/structure/section.html

He was already making part of the TLC, we just forgot to add him to the list 🤦

Adding @AutomatedTester to TLC 🎉

---

site_source_files/content/blog/2020/moving-to-trunk-development.md

Blog post describing the removal of the `master` branch
Moving the default development branch from `master` to `trunk`
The Selenium community wants to make sure that we can improve what we do to make sure that we are inclusive.

[Blog] Moving to Trunk

---

docs_source_files/content/grid/_index.zh-cn.md

- grid/_index.zh-cn.md
Add Chinese translation of "grid_index"
Add Chinese translation of "grid_index"

Add Chinese translation of "grid_index"

---

docs_source_files/content/grid/grid_3/_index.zh-cn.md

- grid_3/_index.zh-cn.md
Add Chinese translation of "grid3_index"
Add Chinese translation of "grid3_index"

Add Chinese translation of "grid3_index"

---

docs_source_files/content/driver_idiosyncrasies/driver_specific_capabilities.zh-cn.md
docs_source_files/content/webdriver/keyboard.zh-cn.md

- webdriver/keyboard.zh-cn.md
- driver_idiosyncrasies/driver_specific_capabilities.zh-cn.md
Update Chinese translation of "keyboard" and "driver_specific_capabilities"

Update Chinese translation of "keyboard" and "driver_specific_capabilities"

---

docs_source_files/content/getting_started_with_webdriver/locating_elements.de.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.en.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.es.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.fr.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.ja.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.ko.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.nl.md
docs_source_files/content/getting_started_with_webdriver/locating_elements.zh-cn.md

Replace “ with double quote

---

docs_source_files/content/webdriver/browser_manipulation.de.md
docs_source_files/content/webdriver/browser_manipulation.en.md
docs_source_files/content/webdriver/browser_manipulation.es.md
docs_source_files/content/webdriver/browser_manipulation.fr.md
docs_source_files/content/webdriver/browser_manipulation.ja.md
docs_source_files/content/webdriver/browser_manipulation.ko.md
docs_source_files/content/webdriver/browser_manipulation.nl.md
docs_source_files/content/webdriver/browser_manipulation.zh-cn.md

Added document for take TakeScreenshot

adding documentation for TakeScreenshot

---

docs_source_files/content/webdriver/browser_manipulation.de.md
docs_source_files/content/webdriver/browser_manipulation.en.md
docs_source_files/content/webdriver/browser_manipulation.es.md
docs_source_files/content/webdriver/browser_manipulation.fr.md
docs_source_files/content/webdriver/browser_manipulation.ja.md
docs_source_files/content/webdriver/browser_manipulation.ko.md
docs_source_files/content/webdriver/browser_manipulation.nl.md
docs_source_files/content/webdriver/browser_manipulation.zh-cn.md

Adding java code for takescreenshot.

Adding java code for takescreenshot

---

docs_source_files/content/webdriver/browser_manipulation.de.md
docs_source_files/content/webdriver/browser_manipulation.en.md
docs_source_files/content/webdriver/browser_manipulation.es.md
docs_source_files/content/webdriver/browser_manipulation.fr.md
docs_source_files/content/webdriver/browser_manipulation.ja.md
docs_source_files/content/webdriver/browser_manipulation.ko.md
docs_source_files/content/webdriver/browser_manipulation.nl.md
docs_source_files/content/webdriver/browser_manipulation.zh-cn.md

kotlin code for takescreenshot

adding kotlin code sample for takescreenshot

---

website_and_docs/content/documentation/webdriver/interactions/virtual_authenticator.pt-br.md

**A PR well described will help maintainers to review and merge it quickly**
Avoid large PRs, and help reviewers by making them as simple and short as possible.
Translation of virtual authenticator page, its topics descriptions, and remove of alert on top of page.
The page was in need of a translation

pt-br translate of virtual authenticator page
